version: '3.9'

services:
  mysqldb:
    image: mysql:latest
    container_name: spotify-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3309:3306"
    networks:
      - springApi-network

  spring-app:
    image: pedrolorencini/spotify-api:latest
    container_name: spring-app
    environment:
      - DB_HOST=mysqldb
    ports:
      - "2595:2595"
    networks:
      - springApi-network
    depends_on:
      - mysqldb

networks:
  springApi-network:
    driver: bridge
